### ISSUE TITLE
Channel Deposit Maximums

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#8]
Right now, we cap the swappable tokens in a channel at 69. This is confusing, however, because if you deposit more than $69 worth of Eth in your channel, you will only be able to see $69. Even more confusing: when you pay afterwards, your balance will not reduce because, in the background, the wallet will be swapping your remaining Eth for more Dai.

I think a better way to do this is to have explicit channel deposit maximums. If a user tries to deposit more than, say, $30, the browser autodeposit function should only deposit $30 worth and return the rest of the funds to the user.

This way, users can always top up more onto their card if they choose but up to the same limit. This will also put some limits on the amount of total collateral in the system, which we can gradually increase with time.

We should also discuss whether it's worth having a more explicit cap on transactable funds (maybe a max payment size?)

**Comment by LayneHaber** [comment]
The display could also use the "total balance" instead of the token/dai balance. 

We should also not send funds back to the user, but instead refuse to accept deposits that are too large. This can be done right now entirely on the UI side.

Could also have an "advanced mode" where the wallet stores the eth that hasnt been converted, and it exchanges as needed. This mode would assume the user had more intimate knowledge about how their channel works, would be confusing for most, but could unlock additional functionality for power users

**Comment by ArjunBhuptani** [comment]
I'm not in favor of "total balance". If we use "total balance", it'll fluctuate with Eth price.

How do we not accept deposits that are too large? We can't fail the tx going to the browser address since that's just a normal address.

Let's leave off advanced mode for now: I want to make sure this is doable in a day before. There's a precedence for channel/network maximums set by Lightning/Raiden, so I see no reason not to just do this.

@rhlsthrm is there something we can do hub side to enforce? Maybe just make sure that a channel will not be collateralized/swapped past $30 or whatever.

**Comment by rhlsthrm** [comment]
I think your idea of having it in the address balance poller is the easiest to implement @ArjunBhuptani. However, I'm not sure we can be absolutely sure which address to send the remaining funds to.

**Comment by ArjunBhuptani** [comment]
Can this be closed?
